### ISSUE TITLE
Does ReadMe instructions for "old Gradle plugins syntax" need an update?

### ISSUE THREAD

**Issue by nacfe** [Banno/Gordon#14]
In the ReadMe file, the instructions for the "old Gradle plugins syntax" are:

```
buildscript {
    repositories {
        gradlePluginPortal()
        google()
        jcenter()
        maven { url "https://jitpack.io" }
    }

    dependencies {
        classpath "com.banno.gordon:gordon-plugin:$gordonVersion"
    }
}
```

But I could only make it work with a slightly different code:

```
buildscript {
    ext.gordonVersion = "1.0.6"
    repositories {
        ...
    }

    dependencies {
        classpath "com.github.Banno:Gordon:$gordonVersion"
    }
}
```

Otherwise it would give an error saying that it couldn't find Gordon in any classpath.

Am I doing something wrong or could you please check if the ReadMe file needs any changes?

**Comment by joshschriever** [comment]
@nacfe the ReadMe should be correct.

`classpath "com.github.Banno:Gordon:$gordonVersion"` makes me think you're getting it from jitpack instead of the gradle plugin portal.

Make sure you have the dependency repositories in the correct order. `gradlePluginPortal()` needs to come before `maven { url "https://jitpack.io" }`.

**Comment by joshschriever** [comment]
Feel free to reopen if the correct repository order doesn't fix your problem.

**Comment by nacfe** [comment]
Thank you @joshschriever
