### ISSUE TITLE
Pass environment variables

### ISSUE THREAD

**Issue by QAutomatron** [Banno/Gordon#20]
How can I pass environment parameters to all tests run through Gordon?

I mean the ones are usually pass in Android as `testInstrumentationRunnerArguments`. Parameters like `clearPackageData: 'true'` or custom ones like `foo: bar`, so in test i can get them using: `InstrumentationRegistry.getArguments().getString("foo")`.
Will it use project-based `testInstrumentationRunnerArguments` or it will override them?

**Comment by joshschriever** [comment]
Gordon will pass along the project's `testInstrumentationRunnerArguments`, so yes, you can get them in tests using `InstrumentationRegistry`.

One thing to note: `clearPackageData` won't do anything by default when using Gordon, because it is specific to Android Test Orchestrator. You could, of course, get `clearPackageData` using `InstrumentationRegistry`, and clear data yourself before tests if that's something you need to do.
